language: java
sudo: required
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - openjdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6
install: true
script:
    echo $JAVA_HOME
    echo $TRAVIS_JDK_VERSION
    if [[ $JAVA_HOME =*java-6* ]]; then
        jdk_switcher use openjdk6;
    fi
    java -version
    echo $TRAVIS_JDK_VERSION
    if [ "$TRAVIS_JDK_VERSION" == "openjdk6" ]; then
      wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip -P ./target;
      unzip -qq ./target/apache-maven-3.2.5-bin.zip -d ./target;
      export M2_HOME=$PWD/target/apache-maven-3.2.5;
      export PATH=$M2_HOME/bin:$JAVA_HOME/bin:$PATH;
      export SETTINGS="-s .travis.settings.xml";
    fi;
    if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package jacoco:report coveralls:report;
    else
      mvn -V -B -e clean package $SETTINGS;
    fi
cache:
  directories:
    - $HOME/.m2
