language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
install: true
script: "mkdir xstream/profiles/coveralls && mvn -V -B -e clean package cobertura:cobertura coveralls:report"
cache:
    directories:
    - $HOME/.m2
