language: java
sudo: false
addons:
  - apt:
    - packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
install: true
script:
    if ( `javac -version 2>&1 | grep '1\.8\.0' > /dev/null` ); then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package cobertura:cobertura coveralls:report;
    else
      mvn -V -B -e clean package;
    fi
cache:
    directories:
    - $HOME/.m2
