language: java
sudo: false
jdk:
  - openjdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
install: true
script:
    export SETTINGS="-s .travis.settings.xml";
    if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then
      mkdir -p xstream/profiles/coveralls;
      mkdir -p xstream-hibernate/profiles/coveralls;
      mvn -V -B -e clean package jacoco:report coveralls:report;
    else
      mvn -V -B -e clean package $SETTINGS;
    fi
cache:
  directories:
    - $HOME/.m2
